"""add column spotify_user_token

Revision ID: 28550d05bbe0
Revises: 
Create Date: 2025-11-12 20:11:24.041221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28550d05bbe0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('spotify_user_token', sa.String(), nullable=True))
    op.add_column('user', sa.Column('spotify_refresh_token', sa.String(), nullable=True))
    op.add_column('user', sa.Column('spotify_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'spotify_expires_at')
    op.drop_column('user', 'spotify_refresh_token')
    op.drop_column('user', 'spotify_user_token')
    # ### end Alembic commands ###
